### ISSUE TITLE
f-string parameter to error message included among raised errors

### ISSUE THREAD

**Issue by tom-f-oconnell** [pixelneo/vim-python-docstring#10]
With this function (reproduced with only this contents in a file too):
```
def f(x, y):
    if x == 1:
        raise ValueError(f'x ({x}) == 1')

    return a, b
```

Calling `:Docstring` produces this docstring:
```
     """

    Args:
        x:
        y:

    Returns:
        

    Raises:
        ValueError:    x:
    """
```

Expected output:
```
     """

    Args:
        x:
        y:

    Returns:
        

    Raises:
        ValueError:
    """
```

It seems related to the f-string.

I'm on Ubuntu 20.04, and my output of `vim --version` is:
[vim_version.txt](https://github.com/pixelneo/vim-python-docstring/files/7652698/vim_version.txt)

One minor README typo I didn't feel was worth a separate issue: Instalation -> Installation
